export interface GlossaryEntry {
  term: string;
  slug: string;
  definition: string;
  analogy: string;
  firstSeenSection: 'hero' | 'tokenization' | 'embeddings' | 'attention' | 'multihead' | 'block' | 'sampling' | 'loop' | 'epilogue';
  category: 'core' | 'attention' | 'architecture' | 'sampling' | 'audio';
}

export const GLOSSARY: GlossaryEntry[] = [
  {
    term: 'Token',
    slug: 'token',
    definition: 'A small chunk of data (a word, part of a word, a note, or an audio slice) represented by a catalogue integer ID.',
    analogy: 'A numbered LEGO brick piece in a construction set.',
    firstSeenSection: 'tokenization',
    category: 'core',
  },
  {
    term: 'Tokenizer',
    slug: 'tokenizer',
    definition: 'A program that splits raw text, notation, or sound into a sequence of tokens based on a fixed vocabulary.',
    analogy: 'A cutter that chops a ribbon of fabric into standard-sized patches.',
    firstSeenSection: 'tokenization',
    category: 'core',
  },
  {
    term: 'Vocabulary',
    slug: 'vocabulary',
    definition: 'The fixed master list of all unique tokens a model knows, mapping each token to an integer ID.',
    analogy: 'A hardware store catalogue where every screw and bolt has an item number.',
    firstSeenSection: 'tokenization',
    category: 'core',
  },
  {
    term: 'ID',
    slug: 'id',
    definition: 'An integer representing a specific token from the vocabulary table (e.g. 412 for "guitar").',
    analogy: 'The barcode number stamped on a specific product box.',
    firstSeenSection: 'tokenization',
    category: 'core',
  },
  {
    term: 'ABC Notation',
    slug: 'abc-notation',
    definition: 'A lightweight, plain-text format for writing musical melodies, rhythms, and chords using standard ASCII letters.',
    analogy: 'A recipe card that tells a musician which notes to play in order using plain keyboard letters.',
    firstSeenSection: 'tokenization',
    category: 'audio',
  },
  {
    term: 'Waveform',
    slug: 'waveform',
    definition: 'A visual or numerical representation of air vibrations over time that produce sound.',
    analogy: 'The physical ripples created on a water surface when a pebble drops.',
    firstSeenSection: 'tokenization',
    category: 'audio',
  },
  {
    term: 'Embedding',
    slug: 'embedding',
    definition: 'A list of numbers (coordinates) that captures what a token means so that similar things sit close together.',
    analogy: 'GPS coordinates on a giant multi-dimensional map of concepts.',
    firstSeenSection: 'embeddings',
    category: 'core',
  },
  {
    term: 'Vector',
    slug: 'vector',
    definition: 'An ordered list of numbers (e.g., [0.2, -0.8, 1.4]) representing a position or direction in space.',
    analogy: 'A list of ingredient measurements in a spice blend.',
    firstSeenSection: 'embeddings',
    category: 'core',
  },
  {
    term: 'Dimension',
    slug: 'dimension',
    definition: 'One individual axis or coordinate slot inside a vector list.',
    analogy: 'One specific slider on an audio mixing desk, such as Bass or Treble.',
    firstSeenSection: 'embeddings',
    category: 'core',
  },
  {
    term: 'Similarity',
    slug: 'similarity',
    definition: 'A calculation measuring how close two vectors are to each other in embedding space.',
    analogy: 'Measuring the walking distance between two coffee shops on a city street map.',
    firstSeenSection: 'embeddings',
    category: 'core',
  },
  {
    term: 'Self-Attention',
    slug: 'self-attention',
    definition: 'A mechanism that lets every token in a sentence look at all other tokens to determine which ones give it context.',
    analogy: 'A meeting room where each participant asks everyone else for input before speaking.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Query',
    slug: 'query',
    definition: 'A vector representing what a token is currently looking for in other tokens.',
    analogy: 'The search query you type into a library search box.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Key',
    slug: 'key',
    definition: 'A vector representing how a token advertises its content to potential queries.',
    analogy: 'The printed title label and tags on the spine of a library book.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Value',
    slug: 'value',
    definition: 'The actual substantive information a token shares if another token pays attention to it.',
    analogy: 'The actual chapter contents inside the library book.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Score',
    slug: 'score',
    definition: 'The raw relevance number obtained by comparing a Query vector with a Key vector (via dot product).',
    analogy: 'A test match score showing how closely an applicant matches a job description.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Dot Product',
    slug: 'dot-product',
    definition: 'An operation where matching numbers of two lists are multiplied together and then added up.',
    analogy: 'Multiplying items bought by their price tag, then summing to get the total cart receipt.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Softmax',
    slug: 'softmax',
    definition: 'A mathematical formula that converts arbitrary scores into positive percentages that sum cleanly to 100%.',
    analogy: 'Slicing up a whole pie so that everyone gets a slice proportional to their score.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Heatmap',
    slug: 'heatmap',
    definition: 'A 2D grid showing the strength of attention weights between all pairs of tokens in a sequence.',
    analogy: 'A weather radar showing where rain clouds are dense versus clear.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Causal Mask',
    slug: 'causal-mask',
    definition: 'A rule that blocks tokens from paying attention to future tokens, preventing the model from peeking ahead.',
    analogy: 'Wearing horse blinders that stop you from looking ahead down the road.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Context',
    slug: 'context',
    definition: 'The surrounding tokens that help resolve the meaning of ambiguous words (like "it" or "rock").',
    analogy: 'The background setting of a conversation that clarifies inside jokes.',
    firstSeenSection: 'attention',
    category: 'attention',
  },
  {
    term: 'Head',
    slug: 'head',
    definition: 'One independent attention calculation running in parallel with its own Query, Key, and Value projections.',
    analogy: 'One specialized camera operator in a broadcast crew focused only on the drummer.',
    firstSeenSection: 'multihead',
    category: 'attention',
  },
  {
    term: 'Multi-Head Attention',
    slug: 'multi-head-attention',
    definition: 'Running multiple attention heads side by side so the model can track multiple relationships simultaneously.',
    analogy: 'A panel of four judges scoring a musical performance from melody, rhythm, lyrics, and tone.',
    firstSeenSection: 'multihead',
    category: 'attention',
  },
  {
    term: 'Concatenate',
    slug: 'concatenate',
    definition: 'Joining multiple lists or vectors end-to-end to form one longer list.',
    analogy: 'Coupling train carriages together into one continuous train line.',
    firstSeenSection: 'multihead',
    category: 'attention',
  },
  {
    term: 'Transformer',
    slug: 'transformer',
    definition: 'The deep learning architecture based on stacked self-attention and feed-forward layers that powers modern generative AI.',
    analogy: 'A multi-stage factory assembly line where each station enriches the product.',
    firstSeenSection: 'block',
    category: 'architecture',
  },
  {
    term: 'Block / Layer',
    slug: 'block',
    definition: 'One repeating modular unit of a transformer, containing self-attention, normalisation, and a feed-forward network.',
    analogy: 'One floor in a multi-story processing department.',
    firstSeenSection: 'block',
    category: 'architecture',
  },
  {
    term: 'Residual Connection',
    slug: 'residual-connection',
    definition: 'A shortcut lane that adds a layer input directly to its output (x = x + layer(x)), preserving original information.',
    analogy: 'A bypass road around a roundabout so express traffic does not get lost.',
    firstSeenSection: 'block',
    category: 'architecture',
  },
  {
    term: 'Normalisation',
    slug: 'normalisation',
    definition: 'Rescaling number lists so their values stay within a stable, comfortable range without exploding or vanishing.',
    analogy: 'An audio sound limiter that keeps volume levels consistent across quiet and loud passages.',
    firstSeenSection: 'block',
    category: 'architecture',
  },
  {
    term: 'Feed-Forward Network',
    slug: 'feed-forward-network',
    definition: 'A small neural network applied to each token vector individually without sharing info between tokens.',
    analogy: 'Each worker sitting at their desk processing their own personal task without consulting neighbours.',
    firstSeenSection: 'block',
    category: 'architecture',
  },
  {
    term: 'Positional Information',
    slug: 'positional-information',
    definition: 'Numbers added to token embeddings so the model knows the sequential order of words or musical notes.',
    analogy: 'Page numbers printed on the bottom of manuscript leaves.',
    firstSeenSection: 'block',
    category: 'architecture',
  },
  {
    term: 'Logits',
    slug: 'logits',
    definition: 'The raw, unnormalized score numbers produced by the final layer of a model for every token in its vocabulary.',
    analogy: 'Unsorted raw tally votes cast in an election before percentages are computed.',
    firstSeenSection: 'sampling',
    category: 'sampling',
  },
  {
    term: 'Sampling',
    slug: 'sampling',
    definition: 'The process of choosing one token from a probability distribution using a pseudo-random roll.',
    analogy: 'Rolling a custom multi-sided die where some faces are wider than others.',
    firstSeenSection: 'sampling',
    category: 'sampling',
  },
  {
    term: 'Temperature',
    slug: 'temperature',
    definition: 'A control dial that adjusts how sharp or flat the probability distribution is before rolling.',
    analogy: 'Adjusting how adventurous or conservative a chef is with unfamiliar spices.',
    firstSeenSection: 'sampling',
    category: 'sampling',
  },
  {
    term: 'Top-K',
    slug: 'top-k',
    definition: 'Filtering rule that discards all candidates except the top K highest-probability tokens.',
    analogy: 'A talent show where only the top 3 finalists proceed to the final vote.',
    firstSeenSection: 'sampling',
    category: 'sampling',
  },
  {
    term: 'Top-P',
    slug: 'top-p',
    definition: 'Filtering rule (nucleus sampling) that retains the smallest group of top tokens whose cumulative probability reaches P.',
    analogy: 'Filling a gift bag with the most popular candies until the bag is 90% full, then stopping.',
    firstSeenSection: 'sampling',
    category: 'sampling',
  },
  {
    term: 'Seed',
    slug: 'seed',
    definition: 'A starting integer given to the pseudorandom number generator to make random generation 100% reproducible.',
    analogy: 'Setting the exact initial gear position on a mechanical clockwork music box.',
    firstSeenSection: 'sampling',
    category: 'sampling',
  },
  {
    term: 'Classifier-Free Guidance (CFG)',
    slug: 'classifier-free-guidance',
    definition: 'A technique that compares a conditioned prediction with an unconditioned one to push output closer to the prompt.',
    analogy: 'A music producer who constantly nudges a band back toward the agreed demo track style.',
    firstSeenSection: 'sampling',
    category: 'sampling',
  },
  {
    term: 'Autoregressive (AR)',
    slug: 'autoregressive',
    definition: 'A generation process where each new item is generated one after another, feeding newly made items back into the context.',
    analogy: 'Typing on your smartphone keyboard, where each selected word helps suggest the next one.',
    firstSeenSection: 'loop',
    category: 'architecture',
  },
  {
    term: 'Non-Autoregressive (NAR)',
    slug: 'non-autoregressive',
    definition: 'A generation process where all parts of an output are created or refined simultaneously in parallel passes.',
    analogy: 'A painter laying down background color across an entire canvas at once rather than pixel-by-pixel.',
    firstSeenSection: 'loop',
    category: 'architecture',
  },
  {
    term: 'Stop Token',
    slug: 'stop-token',
    definition: 'A special token emitted by the model to indicate that generation is complete and the loop should halt.',
    analogy: 'The word "STOP" stamped at the end of a telegram message.',
    firstSeenSection: 'loop',
    category: 'sampling',
  },
  {
    term: 'Flow Matching',
    slug: 'flow-matching',
    definition: 'A generative technique that smoothly transforms pure noise into structured audio details via velocity vectors.',
    analogy: 'A sculptor gradually smoothing a rough block of clay into a fine statue across several gentle passes.',
    firstSeenSection: 'loop',
    category: 'audio',
  },
  {
    term: 'Semantic Tokens',
    slug: 'semantic-tokens',
    definition: 'Discrete tokens representing high-level musical structure, phrasing, lyrics, and pitch contours.',
    analogy: 'A playwright script outlining which actor sings what line in each act.',
    firstSeenSection: 'loop',
    category: 'audio',
  },
  {
    term: 'Acoustic Latents',
    slug: 'acoustic-latents',
    definition: 'Dense numerical representations capturing fine-grained sound texture, timbre, harmonics, and stereo width.',
    analogy: 'The microscopic audio groove details pressed into a vinyl record.',
    firstSeenSection: 'loop',
    category: 'audio',
  },
  {
    term: 'VAE (Variational Autoencoder)',
    slug: 'vae',
    definition: 'A neural compression model that translates between compact audio latents and raw audible stereo sound waves.',
    analogy: 'An MP3 decompressor that expands compressed file data back into audio vibrations.',
    firstSeenSection: 'epilogue',
    category: 'audio',
  },
];
